import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body className={inter.className}>
      <nav className='w-full flex justify-center gap-5'>
       <Link href="/">home</Link>
       <Link href="/posts">posts</Link>
       <Link href="/articles">articles</Link>
       <Link href="/articles/featuredArticles">featured Articles</Link>

      </nav>
        
        
        {children}
        
        </body>
    </html>
  )
}
